server:
  port: 8088

spring:
  application:
    name: alibaba-deepseek-demo

  ai:
    openai:
        # 这写你自己的api！
      api-key: your-openai-api-key
      base-url: https://api.siliconflow.cn
      chat:
        options:
          model: Qwen/Qwen2.5-72B-Instruct
