server:
  port: 9001

spring:
  application:
    name: tlmall-ai
  threads:
    virtual:
      enabled: true
  mvc:
    static-path-pattern: /templates/**
  thymeleaf:
    cache: false

  ai:
    dashscope:
      api-key: ${AI_DASHSCOPE_API_KEY}
#      chat:
#        options:
#          model: qwen-max