spring:
  application:
    name: Rag-milvus-demo

  ai:
    dashscope:
      api-key: ${AI_DASHSCOPE_API_KEY}

    vectorstore:
      milvus:
        client:
          host: "192.168.65.217" # default: localhost
          port: 19530 # default: 19530
          username: "root" # default: root
          password: "Milvus" # default: milvus
        databaseName: "default"
        collectionName: "vector_store" # default: vector_store
        embeddingDimension: 1536 # default: 1536
        indexType: IVF_FLAT # default: IVF_FLAT
        metricType: COSINE # default: COSINE
        initialize-schema: true # 自动创建集合

