server:
  port: 8092

spring:
  application:
    name: alibaba-deepseek-demo

  # 静态资源配置
  web:
    resources:
      static-locations: classpath:/static/
      cache:
        period: 0

  # MVC配置
  mvc:
    static-path-pattern: /**
    view:
      prefix: /
      suffix: .html

  ai:
    openai:
        # 这写你自己的api！
      api-key: sk-yrihxgdcfjrhjdzknhyteeblftqshdrcphjzehnljshiiipu
      base-url: https://api.siliconflow.cn
      chat:
        options:
          model: Qwen/Qwen2.5-72B-Instruct

# 日志配置
logging:
  level:
    com.fox.alibabadeepseekdemo: DEBUG
