server:
  port: 8088

spring:
  application:
    name: alibaba-deepseek-demo


  ai:
    ollama:
      base-url: http://localhost:11434
      chat:
        model: deepseek-r1:1.5b

#    openai:
#      api-key: ${AI_SILICONFLOW_API_KEY}
#      base-url: https://api.siliconflow.cn
#      chat:
#        options:
#          model: Qwen/Qwen2.5-72B-Instruct


#    dashscope:
#      api-key: ${AI_DASHSCOPE_API_KEY}
#      #base-url: https://dashscope.aliyuncs.com/compatible-mode/v1
#      chat:
#        options:
#          model: qwen-max


