server:
  port: 8088

spring:
  application:
    name: alibaba-deepseek-demo

  ai:
    openai:
      api-key: sk-sljpozhxgzovbzzpwznptdylmnbmoxiagdntqhiiyydarcjp
      base-url: https://api.siliconflow.cn
      chat:
        options:
          model: Qwen/Qwen2.5-72B-Instruct
